//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookmarkManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookmarkManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project website:.
        /// </summary>
        public static string AboutWebsite {
            get {
                return ResourceManager.GetString("AboutWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string AddCategoryButton {
            get {
                return ResourceManager.GetString("AddCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        public static string AddLinkButton {
            get {
                return ResourceManager.GetString("AddLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string BookmarkMenu {
            get {
                return ResourceManager.GetString("BookmarkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all in browser.
        /// </summary>
        public static string BookmarkOpenAllMenuItem {
            get {
                return ResourceManager.GetString("BookmarkOpenAllMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string BookmarkOpenMenuItem {
            get {
                return ResourceManager.GetString("BookmarkOpenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Tor Browser.
        /// </summary>
        public static string BookmarkOpenTorMenuItem {
            get {
                return ResourceManager.GetString("BookmarkOpenTorMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks:.
        /// </summary>
        public static string BookmarksLabel {
            get {
                return ResourceManager.GetString("BookmarksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CategoryDeleteMenuItem {
            get {
                return ResourceManager.GetString("CategoryDeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryMenu {
            get {
                return ResourceManager.GetString("CategoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting category will delete all bookmarks in this category. Are you sure want to delete them?.
        /// </summary>
        public static string CategoryRemovalText {
            get {
                return ResourceManager.GetString("CategoryRemovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category removal.
        /// </summary>
        public static string CategoryRemovalTitle {
            get {
                return ResourceManager.GetString("CategoryRemovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config loading error.
        /// </summary>
        public static string ConfigLoadingError {
            get {
                return ResourceManager.GetString("ConfigLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config saving error.
        /// </summary>
        public static string ConfigSavingError {
            get {
                return ResourceManager.GetString("ConfigSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextCategoryDelete {
            get {
                return ResourceManager.GetString("ContextCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file:.
        /// </summary>
        public static string CurrentFileStatusBar {
            get {
                return ResourceManager.GetString("CurrentFileStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBookmarkMenuItem {
            get {
                return ResourceManager.GetString("DeleteBookmarkMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap deleterecord {
            get {
                object obj = ResourceManager.GetObject("deleterecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening link in Tor Browser.
        /// </summary>
        public static string ErrorOpeningInTor {
            get {
                return ResourceManager.GetString("ErrorOpeningInTor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FileExitMenuItem {
            get {
                return ResourceManager.GetString("FileExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loading error.
        /// </summary>
        public static string FileLoadingError {
            get {
                return ResourceManager.GetString("FileLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuItem {
            get {
                return ResourceManager.GetString("FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FileNewMenuItem {
            get {
                return ResourceManager.GetString("FileNewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpenMenuItem {
            get {
                return ResourceManager.GetString("FileOpenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string FileRecentMenuItem {
            get {
                return ResourceManager.GetString("FileRecentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSaveMenuItem {
            get {
                return ResourceManager.GetString("FileSaveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saving error.
        /// </summary>
        public static string FileSavingError {
            get {
                return ResourceManager.GetString("FileSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FileSettingsMenuItem {
            get {
                return ResourceManager.GetString("FileSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap newdb {
            get {
                object obj = ResourceManager.GetObject("newdb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose filename for new database.
        /// </summary>
        public static string NewDbFilenameSelection {
            get {
                return ResourceManager.GetString("NewDbFilenameSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap newrecord {
            get {
                object obj = ResourceManager.GetObject("newrecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap opendb {
            get {
                object obj = ResourceManager.GetObject("opendb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap savedb {
            get {
                object obj = ResourceManager.GetObject("savedb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set path to Tor Browser in File -&gt; Settings.
        /// </summary>
        public static string SetPathToTorMessage {
            get {
                return ResourceManager.GetString("SetPathToTorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsCancelButton {
            get {
                return ResourceManager.GetString("SettingsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear last used files list.
        /// </summary>
        public static string SettingsClearRecentList {
            get {
                return ResourceManager.GetString("SettingsClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        public static string SettingsCloseToTray {
            get {
                return ResourceManager.GetString("SettingsCloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open last used file.
        /// </summary>
        public static string SettingsOpenLastFile {
            get {
                return ResourceManager.GetString("SettingsOpenLastFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsSaveButton {
            get {
                return ResourceManager.GetString("SettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in taskbar.
        /// </summary>
        public static string SettingsShowInTaskbar {
            get {
                return ResourceManager.GetString("SettingsShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string SettingsStartMinimized {
            get {
                return ResourceManager.GetString("SettingsStartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string SettingsStartWithWindows {
            get {
                return ResourceManager.GetString("SettingsStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookmarkManager settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor Browser path:.
        /// </summary>
        public static string SettingTorPath {
            get {
                return ResourceManager.GetString("SettingTorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor Browser not found.
        /// </summary>
        public static string TorNotFound {
            get {
                return ResourceManager.GetString("TorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total bookmarks:.
        /// </summary>
        public static string TotalBookmarksStatusBar {
            get {
                return ResourceManager.GetString("TotalBookmarksStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total categories:.
        /// </summary>
        public static string TotalCategoriesStatusBar {
            get {
                return ResourceManager.GetString("TotalCategoriesStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark from clipboard.
        /// </summary>
        public static string TrayMenuBookmarkFromClipboard {
            get {
                return ResourceManager.GetString("TrayMenuBookmarkFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open main window.
        /// </summary>
        public static string TrayMenuOpenMainWindow {
            get {
                return ResourceManager.GetString("TrayMenuOpenMainWindow", resourceCulture);
            }
        }
    }
}
